/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ApiStreamIdRouteImport } from './routes/api/stream.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamIdRoute = ApiStreamIdRouteImport.update({
  id: '/api/stream/$id',
  path: '/api/stream/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/rtc': typeof ApiRtcRoute
  '/r/$code': typeof RCodeRoute
  '/api/stream/$id': typeof ApiStreamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/rtc': typeof ApiRtcRoute
  '/r/$code': typeof RCodeRoute
  '/api/stream/$id': typeof ApiStreamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/rtc': typeof ApiRtcRoute
  '/r/$code': typeof RCodeRoute
  '/api/stream/$id': typeof ApiStreamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/rtc' | '/r/$code' | '/api/stream/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/rtc' | '/r/$code' | '/api/stream/$id'
  id: '__root__' | '/' | '/api/rtc' | '/r/$code' | '/api/stream/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRtcRoute: typeof ApiRtcRoute
  RCodeRoute: typeof RCodeRoute
  ApiStreamIdRoute: typeof ApiStreamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$id': {
      id: '/api/stream/$id'
      path: '/api/stream/$id'
      fullPath: '/api/stream/$id'
      preLoaderRoute: typeof ApiStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRtcRoute: ApiRtcRoute,
  RCodeRoute: RCodeRoute,
  ApiStreamIdRoute: ApiStreamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
